# ========================================================
# POLÍTICA DE ROTACIÓN Y MANTENIMIENTO DE LOGS (Logrotate)
# Proyecto: CentralLog-Architecture
# ========================================================

# Aplica para todos los archivos .log dentro de las subcarpetas de logs remotos
/var/log/remote/*/*.log {
    weekly                  # Rotar los archivos una vez a la semana
    rotate 4                # Conservar un historial de 4 semanas (1 mes de evidencia)
    compress                # Comprimir los logs viejos en formato .gz para ahorrar espacio
    delaycompress           # No comprimir el log de la semana anterior de inmediato (por si se necesita auditar rápido)
    missingok               # Si la carpeta de un host está vacía, no lanzar error
    notifempty              # No rotar el archivo si está totalmente vacío
    create 0640 root adm    # Crear el nuevo archivo vacío con permisos seguros para administración
    sharedscripts           # Ejecutar el script de post-rotación una sola vez por lote
    postrotate
        /usr/lib/rsyslog/rsyslog-rotate
    endscript
}
