# ==========================================
# CentralLog-Architecture: Server Configuration
# ==========================================

# Habilitar la recepción de logs por UDP (Puerto 514)
module(load="imudp")
input(type="imudp" port="514")

# Habilitar la recepción de logs por TCP (Puerto 514)
module(load="imptcp")
input(type="imptcp" port="514")

# ------------------------------------------
# REGLA DE ALMACENAMIENTO DINÁMICO (Plantilla)
# ------------------------------------------
# Esta plantilla organiza los logs entrantes automáticamente.
# Crea una carpeta por cada IP/Nombre de cliente y un archivo por cada servicio.
# Ejemplo: /var/log/remote/192.168.0.X/sshd.log
template(name="RemoteLogs" type="string" string="/var/log/remote/%HOSTNAME%/%PROGRAMNAME%.log")

# Aplicar la plantilla a todos los logs que lleguen desde la red
*.* ?RemoteLogs

# Detener el procesamiento de logs remotos aquí para que no se mezclen con los locales del servidor
& stop
