# ========================================================
# CONFIGURACIÓN DEL SERVIDOR CENTRALIZADOR (Rsyslog Server)
# Proyecto: CentralLog-Architecture
# ========================================================

# 1. Módulos de escucha en red (Puerto 514)
# --------------------------------------------------------
module(load="imudp")
input(type="imudp" port="514")

module(load="imtcp")
input(type="imtcp" port="514")

# 2. Plantillas de almacenamiento dinámico (Templates)
# --------------------------------------------------------
# Separa los logs según el nombre de la máquina origen y el servicio.
# Guarda todo de forma segura en /var/log/remote/<hostname>/<programa>.log

template(name="RemoteLogs" type="string" string="/var/log/remote/%HOSTNAME%/%programname%.log")

# 3. Reglas de filtrado y enrutamiento
# --------------------------------------------------------
# Captura los logs locales y remotos, y los organiza dinámicamente 
# en carpetas separadas según el nombre del host de origen.

*.* action(type="omfile" dynaFile="RemoteLogs")
