# ========================================================
# CONFIGURACIÓN DEL SERVIDOR CENTRALIZADOR (Rsyslog Server)
# Proyecto: CentralLog-Architecture
# ========================================================

# 1. Módulos de escucha en red (Puerto 514)
# --------------------------------------------------------
module(load="imudp")
input(type="imudp" port="514")

module(load="imtcp")
input(type="imtcp" port="514")

# 2. Plantillas de almacenamiento dinámico (Templates)
# --------------------------------------------------------
# Separa los logs según el nombre de la máquina origen y el servicio.
# Guarda todo de forma segura en /var/log/remote/<hostname>/<programa>.log

template(name="RemoteLogs" type="string" string="/var/log/remote/%HOSTNAME%/%programname%.log")

# 3. Reglas de filtrado y enrutamiento
# --------------------------------------------------------
# Si el log se genera localmente o llega por red con origen 'soc-lab',
# se aplica la plantilla para organizarlo en su ruta correspondiente.

if $hostname == 'soc-lab' then {
    action(type="omfile" dynaFile="RemoteLogs")
    stop
}
