# ========================================================
# CONFIGURACIÓN DEL AGENTE EMISOR (Rsyslog Client)
# Proyecto: CentralLog-Architecture
# ========================================================

# 1. Reglas de Envío de Telemetría Crítica
# --------------------------------------------------------
# Selecciona los servicios esenciales del sistema y los redirige
# al servidor centralizador usando el protocolo TCP (identificado por @@).

# Eventos del núcleo del sistema (Kernel)
kern.* @@192.168.0.179:514

# Eventos de autenticación y seguridad (Login, sudo, accesos)
auth,authpriv.* @@192.168.0.179:514

# Logs generales del sistema y demonios (Systemd, servicios)
syslog,daemon.* @@192.168.0.179:514

# 2. Mecanismo de Resiliencia en Alta Disponibilidad (Spool/Queue)
# --------------------------------------------------------
# Si el servidor centralizador no está disponible temporalmente, 
# los logs se guardan en el disco local para evitar la pérdida de evidencia.

$ActionQueueType LinkedList       # Mantiene una cola dinámica en memoria
$ActionQueueFileName client_spool # Nombre base de los archivos de respaldo en disco
$ActionResumeRetryCount -1        # Reintentos infinitos si el servidor se cae
$ActionQueueSaveOnShutdown on     # Salva la cola en disco si el PC se apaga
